In [1]:
import json
import pandas as pd
import os
import shutil
import numpy as np
import scipy as sp

DATA_DIR = "../data"
DATA_FILE = os.path.join(DATA_DIR, "data.json")
DUMP_FILE = os.path.join(DATA_DIR, "dump.pkl")

store_columns = (
    "id",  # 음식점 고유번호
    "store_name",  # 음식점 이름
    "branch",  # 음식점 지점 여부
    "area",  # 음식점 위치
    "tel",  # 음식점 번호
    "address",  # 음식점 주소
    "latitude",  # 음식점 위도
    "longitude",  # 음식점 경도
    "category",  # 음식점 카테고리
    "review_cnt", # 리뷰 개수
)

review_columns = (
    "id",  # 리뷰 고유번호
    "store",  # 음식점 고유번호
    "user",  # 유저 고유번호
    "score",  # 평점
    "content",  # 리뷰 내용
    "reg_time",  # 리뷰 등록 시간
)

user_columns = (
    "id", # 유저 고유 번호
    "gender", # 유저 성별
    "born_year", # 유저 생년
    "review", # 리뷰 고유 번호
)


def import_data(data_path=DATA_FILE):
    """
    Req. 1-1-1 음식점 데이터 파일을 읽어서 Pandas DataFrame 형태로 저장합니다
    """

    try:
        with open(data_path, encoding="utf-8") as f:
            data = json.loads(f.read())
    except FileNotFoundError as e:
        print(f"`{data_path}` 가 존재하지 않습니다.")
        exit(1)

    stores = []  # 음식점 테이블
    reviews = []  # 리뷰 테이블
    users = [] # 유저 테이블

    for d in data:

        categories = [c["category"] for c in d["category_list"]]
        stores.append(
            [
                d["id"],
                d["name"],
                d["branch"],
                d["area"],
                d["tel"],
                d["address"],
                d["latitude"],
                d["longitude"],
                "|".join(categories),
                d["review_cnt"]
            ]
        )

        for review in d["review_list"]:
            r = review["review_info"]
            u = review["writer_info"]

            reviews.append(
                [r["id"], d["id"], u["id"], r["score"], r["content"], r["reg_time"]]
            )

            users.append(
                [u["id"], u["gender"], u["born_year"], r["id"]]
            )



    store_frame = pd.DataFrame(data=stores, columns=store_columns)
    review_frame = pd.DataFrame(data=reviews, columns=review_columns)
    user_frame = pd.DataFrame(data=users, columns=user_columns)

    return {"stores": store_frame, "reviews": review_frame, "users": user_frame}


def dump_dataframes(dataframes):
    pd.to_pickle(dataframes, DUMP_FILE)


def load_dataframes():
    return pd.read_pickle(DUMP_FILE)


def main():

    print("[*] Parsing data...")
    data = import_data()
    print("[+] Done")

    print("[*] Dumping data...")
    dump_dataframes(data)
    print("[+] Done\n")

    data = load_dataframes()

    term_w = shutil.get_terminal_size()[0] - 1
    separater = "-" * term_w

    print("[음식점]")
    print(f"{separater}\n")
    print(data["stores"].head())
    print(f"\n{separater}\n\n")

    print("[리뷰]")
    print(f"{separater}\n")
    print(data["reviews"].head())
    print(f"\n{separater}\n\n")


if __name__ == "__main__":
    main()

[*] Parsing data...
[+] Done
[*] Dumping data...
[+] Done

[음식점]
-----------------------------------------------------------------------------------------------------------------------

   id     store_name branch  area            tel                address  \
0   1           Agal   None    홍대  010-6689-5886   서울특별시 마포구 동교동 170-13
1   2         Assisy   None    광주   062-367-0700    광주광역시 서구 농성동 631-33
2   3  Battered Sole   None   이태원    02-749-6867   서울특별시 용산구 이태원동 118-9
3   4      Chakyoung   None  달맞이길   051-756-5566  부산광역시 해운대구 중2동 1509-5
4   5       Delabobo   None   발산역   02-2667-9854      서울특별시 강서구 등촌동 689

    latitude   longitude   category  review_cnt
0  37.556862  126.926666   아구찜|포장마차           0
1  35.150746  126.890062         카페           0
2  37.535032  126.991664    피쉬앤칩스|펍           0
3  35.158587  129.175004  레스토랑|카프레제           0
4  37.559904  126.840512  디저트카페|디저트           0

-----------------------------------------------------------------------------------------------------------------------


[리뷰]
-----------------------------------------------------------------------------------------------------------------------

   id  store    user  score  \
0   1     15   68632      5
1   2     18  389728      5
2   3     19   68716      4
3   4     37  774353      2
4   5     38  115682      3

                                             content             reg_time
0         전포 윗길에 새로 생긴! 호주에서 온 쉐프가 직접 요리하는 호주식 레스토랑!  1970-01-01 00:00:00
1                    샌드위치 내용물도 알차게 들어있고 맛있었어요 가성비 추천  1970-01-01 00:00:00
2  홈플러스 1층 매장 푸드코트 내 있는 매장인데 계란찜정식은 처음보고 시켜봣는데 사진...  1970-01-01 00:00:00
3  전 여기 5년전에 가봤었는데 그때 기억은 별로였어요\n단체손님이 많았고, 차려지는건...  1970-01-01 00:00:00
4  친구들끼리 술 간단하게마시러 감. 스끼다시 괜찮지만 회 양이 조금 부족한 느낌. 맛...  2019-03-15 22:16:47

-----------------------------------------------------------------------------------------------------------------------

In [2]:
import itertools
from collections import Counter
from parse import load_dataframes
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
from scipy.sparse import csr_matrix


font_list = fm.findSystemFonts(fontpaths=None, fontext="ttf")
if any(["notosanscjk" in font.lower() for font in font_list]):
    plt.rcParams["font.family"] = "Noto Sans CJK JP"
else:
    if not any(["malgun" in font.lower() for font in font_list]):
        raise Exception(
            "Font missing, please install Noto Sans CJK or Malgun Gothic. If you're using ubuntu, try `sudo apt install fonts-noto-cjk`"
        )

    plt.rcParams["font.family"] = "Malgun Gothic"

sns.set_palette(sns.color_palette("Spectral"))
plt.rc("xtick", labelsize=6)


data = load_dataframes()

In [3]:
users = data["users"][["id", "review"]]
print(users)

           id  review
0       68632       1
1      389728       2
2       68716       3
3      774353       4
4      115682       5
...       ...     ...
91393   17371    2401
91394  198050    2402
91395  190766    2403
91396  201564    2404
91397  611078    2405

[91398 rows x 2 columns]

In [4]:
reviews = data["reviews"][["id", "store", "user", "score"]]
reviews.rename(columns = {'id' : 'review_id'}, inplace=True)

print(reviews)

       review_id   store    user  score
0              1      15   68632      5
1              2      18  389728      5
2              3      19   68716      4
3              4      37  774353      2
4              5      38  115682      3
...          ...     ...     ...    ...
91393       2401  360499   17371      5
91394       2402  360505  198050      4
91395       2403  360514  190766      5
91396       2404  360514  201564      4
91397       2405  360515  611078      5

[91398 rows x 4 columns]

C:\Users\hurea\anaconda3\lib\site-packages\pandas\core\frame.py:5034: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [5]:
stores = data["stores"][["id", "store_name"]]
print(stores)

            id     store_name
0            1           Agal
1            2         Assisy
2            3  Battered Sole
3            4      Chakyoung
4            5       Delabobo
...        ...            ...
459983  459996         행복부대찌개
459984  459997           행복부페
459985  459998           행복분식
459986  459999           행복분식
459987  460000           행복분식

[459988 rows x 2 columns]

In [6]:
users_and_reviews = pd.merge(left=users, right=reviews, left_on = ["id", "review"], right_on = ["user", "review_id"])[["id", "store", "score"]]
user_and_review = pd.merge(left = users_and_reviews, right = stores, left_on = "store", right_on = "id", how = "left")[["id_x", "store", "score", "store_name"]].reset_index()
user_and_review.rename(columns = {'id_x' : 'user_id'}, inplace=True)
print(user_and_review)

       index  user_id   store  score  store_name
0          0    68632      15      5         써리힐
1          1   389728      18      5    진삼미 샌드위치
2          2    68716      19      4  한옥마을 전주비빔밥
3          3   774353      37      2       007식당
4          4   115682      38      3       010수산
...      ...      ...     ...    ...         ...
91693  91693    17371  360499      5    지구촌한우생고기
91694  91694   198050  360505      4        지군포차
91695  91695   190766  360514      5          지글
91696  91696   201564  360514      4          지글
91697  91697   611078  360515      5          지글

[91698 rows x 5 columns]

In [10]:
# 평점이 5개 이상 있는 음식점 데이터
store_rating = data["stores"][['id', 'store_name', 'review_cnt']]
store_rating = store_rating[store_rating['review_cnt']>5]
print(store_rating)

            id   store_name  review_cnt
148        149  101번지 남산돈까스          11
220        221          10Q          12
549        550         17도씨           6
641        642    1967 바다지음          10
1712      1713          29펍           6
...        ...          ...         ...
359524  359537         중화복춘           9
359614  359627          중화원           6
359615  359628          중화원           8
360451  360464          지구당          26
360454  360467          지구당           6

[2284 rows x 3 columns]

In [13]:
store_review = pd.merge(left = user_and_review, right = store_rating, left_on = 'store', right_on = 'id')[['user_id', 'store', 'score', 'store_name_x']]
store_review.rename(columns = {'store_name_x' : 'store_name'}, inplace=True)
store_review.rename(columns = {'store' : 'store_id'}, inplace=True)
store_review

       user_id  store_id  score store_name
0       293161    250217      4        신발원
1       293161    250217      4        신발원
2       788031    250217      3        신발원
3       352994    250217      1        신발원
4        10859    250217      5        신발원
...        ...       ...    ...        ...
24359   745622    360467      4        지구당
24360   280855    360467      5        지구당
24361   128271    360467      5        지구당
24362   811088    360467      4        지구당
24363   356252    360467      4        지구당

[24364 rows x 4 columns]

피벗 테이블을 이용해 user - store name 매트릭스 구성

In [15]:
ratings_matrix = store_review.pivot_table('score', index = 'user_id', columns='store_name').fillna(0)
print(ratings_matrix)

store_name  101번지 남산돈까스  10Q  17도씨  1967 바다지음  29펍  33하우스  3일한우국밥  4SEED  \
user_id
23                  0.0  0.0   0.0        0.0  0.0    0.0     0.0    0.0
105                 0.0  0.0   0.0        0.0  0.0    0.0     0.0    0.0
137                 0.0  0.0   0.0        0.0  0.0    0.0     0.0    0.0
147                 0.0  0.0   0.0        0.0  0.0    0.0     0.0    0.0
162                 0.0  0.0   0.0        0.0  0.0    0.0     0.0    0.0
...                 ...  ...   ...        ...  ...    ...     ...    ...
948691              0.0  0.0   0.0        0.0  0.0    0.0     0.0    0.0
949019              0.0  0.0   0.0        0.0  0.0    0.0     0.0    0.0
949596              0.0  0.0   0.0        0.0  0.0    0.0     0.0    0.0
949670              0.0  0.0   0.0        0.0  0.0    0.0     0.0    0.0
950224              0.0  0.0   0.0        0.0  0.0    0.0     0.0    0.0

store_name  4브라더스  5.5닭갈비  ...  중식당 청담  중앙관  중앙닭강정  중앙떡볶이  중앙식당  중앙해장  중평떡볶이  \
user_id                    ...
23            0.0     0.0  ...     0.0  0.0    0.0    0.0   0.0   0.0    0.0
105           0.0     0.0  ...     0.0  0.0    0.0    0.0   0.0   0.0    0.0
137           0.0     0.0  ...     0.0  0.0    0.0    0.0   0.0   0.0    0.0
147           0.0     0.0  ...     0.0  0.0    0.0    0.0   0.0   0.0    0.0
162           0.0     0.0  ...     0.0  0.0    0.0    0.0   0.0   0.0    0.0
...           ...     ...  ...     ...  ...    ...    ...   ...   ...    ...
948691        0.0     0.0  ...     0.0  0.0    0.0    0.0   0.0   0.0    0.0
949019        0.0     0.0  ...     0.0  0.0    0.0    0.0   0.0   0.0    0.0
949596        0.0     0.0  ...     0.0  0.0    0.0    0.0   0.0   0.0    0.0
949670        0.0     0.0  ...     0.0  0.0    0.0    0.0   0.0   0.0    0.0
950224        0.0     0.0  ...     0.0  0.0    0.0    0.0   0.0   0.0    0.0

store_name  중화복춘  중화원  지구당
user_id
23           0.0  0.0  0.0
105          0.0  0.0  0.0
137          0.0  0.0  0.0
147          0.0  0.0  0.0
162          0.0  0.0  0.0
...          ...  ...  ...
948691       0.0  0.0  0.0
949019       0.0  0.0  0.0
949596       0.0  0.0  0.0
949670       0.0  0.0  0.0
950224       0.0  0.0  0.0

[8046 rows x 2017 columns]

음식점 x 사용자 매트릭스로 변환

In [16]:
ratings_matrix_T = ratings_matrix.transpose()
ratings_matrix_T

user_id,23,105,137,147,162,166,172,182,189,218,...,947927,948202,948319,948416,948690,948691,949019,949596,949670,950224
store_name,,,,,,,,,,,,,,,,,,,,,
101번지 남산돈까스,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10Q,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17도씨,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1967 바다지음,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29펍,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
중앙해장,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
중평떡볶이,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
중화복춘,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
중화원,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
지구당,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

item-user matrix에서 cosine similarity 사용

In [21]:
from sklearn.metrics.pairwise import cosine_similarity
item_sim = cosine_similarity(ratings_matrix_T, ratings_matrix_T)

item_sim_df = pd.DataFrame(data = item_sim, index = ratings_matrix.columns, columns = ratings_matrix.columns)
print(item_sim_df.head(3))

store_name   101번지 남산돈까스  10Q      17도씨  1967 바다지음       29펍  33하우스    3일한우국밥  \
store_name
101번지 남산돈까스     1.000000  0.0  0.082747        0.0  0.000000    0.0  0.147723
10Q             0.000000  1.0  0.000000        0.0  0.000000    0.0  0.000000
17도씨            0.082747  0.0  1.000000        0.0  0.127071    0.0  0.000000

store_name   4SEED  4브라더스  5.5닭갈비  ...  중식당 청담  중앙관  중앙닭강정  중앙떡볶이  중앙식당  중앙해장  \
store_name                         ...
101번지 남산돈까스    0.0    0.0     0.0  ...     0.0  0.0    0.0    0.0   0.0   0.0
10Q            0.0    0.0     0.0  ...     0.0  0.0    0.0    0.0   0.0   0.0
17도씨           0.0    0.0     0.0  ...     0.0  0.0    0.0    0.0   0.0   0.0

store_name   중평떡볶이      중화복춘  중화원  지구당
store_name
101번지 남산돈까스    0.0  0.000000  0.0  0.0
10Q            0.0  0.000000  0.0  0.0
17도씨           0.0  0.105564  0.0  0.0

[3 rows x 2017 columns]

음식점 이름 목록

In [22]:
ratings_matrix.columns

Index(['101번지 남산돈까스', '10Q', '17도씨', '1967 바다지음', '29펍', '33하우스', '3일한우국밥',
       '4SEED', '4브라더스', '5.5닭갈비',
       ...
       '중식당 청담', '중앙관', '중앙닭강정', '중앙떡볶이', '중앙식당', '중앙해장', '중평떡볶이', '중화복춘',
       '중화원', '지구당'],
      dtype='object', name='store_name', length=2017)

3일한우국밥과 유사도가 높은 음식점 5개 추천

In [25]:
item_sim_df['3일한우국밥'].sort_values(ascending=False)[1:6]

store_name
다케       0.279822
목동분식     0.252399
대관원      0.250156
사모님짬뽕    0.247739
이조보쌈     0.239397
Name: 3일한우국밥, dtype: float64

중앙관과 유사도가 높은 음식점 5개 추천

In [26]:
item_sim_df['중앙관'].sort_values(ascending=False)[1:6]

store_name
닭발집      0.405906
우리분식     0.253796
놈파스타     0.235320
빈해원      0.223551
방콕야시장    0.219508
Name: 중앙관, dtype: float64

### TOP-N

TOP-N을 쓰는 이유는 특정 item과 가장 비슷한 n개의 item들만 유사도 계산에 사용하기 위해서임

In [32]:
def predict_rating_topsim(ratings_arr, item_sim_arr, n = 20):
    pred = np.zeros(ratings_arr.shape)
    
    # user-item의 item 개수 만큼 loop
    for col in range(ratings_arr.shape[1]):
        # 유사도가 큰 순으로 n개의 데이터 행렬의 index 반환
        top_n_items = [np.argsort(item_sim_arr[:, col])[:-n-1:-1]]
        # 각 item 별로 전체 사용자들의 예측 평점
        for row in range(ratings_arr.shape[0]):
            pred[row, col] = item_sim_arr[col, :][top_n_items].dot(ratings_arr[row, :][top_n_items].T)
            pred[row, col] /= np.sum(item_sim_arr[col, :][top_n_items])
    return pred

293161 유저에게 음식점 추천

해당 유저가 방문한 음식점 리스트

In [28]:
username = 293161

user_rating_id = ratings_matrix.loc[username, :]
user_rating_id[user_rating_id > 0].sort_values(ascending=False)[:10]

store_name
동복리 해녀촌    5.0
루엘드파리      5.0
우진해장국      5.0
거대         4.0
금산제면소      4.0
마가만두       4.0
명진전복       4.0
봉산옥        4.0
블랙업커피      4.0
삼촌네        4.0
Name: 293161, dtype: float64

user가 방문하지 않은 음식점 추천하기

In [29]:
def not_visited_store(ratings_matrix, user_id):
    # user_id가 방문한 음식점 list
    user_rating = ratings_matrix.loc[user_id, :]
    visited = user_rating[user_rating>0].index.tolist()
    
    # 모든 store list로 만들기
    store_list = ratings_matrix.columns.tolist()
    
    # user가 방문한 음식점은 제외
    not_visited = [i for i in store_list if i not in visited]
    return not_visited

In [34]:
def recomm_store_by_user(pred_df, user_id, not_visited, top_n):
    recomm_store = pred_df.loc[user_id, not_visited].sort_values(ascending=False)[:top_n]
    return recomm_store

user가 방문하지 않은 음식점

In [31]:
not_visit = not_visited_store(ratings_matrix, 293161)
not_visit

['101번지 남산돈까스',
 '10Q',
 '17도씨',
 '1967 바다지음',
 '29펍',
 '33하우스',
 '3일한우국밥',
 '4SEED',
 '4브라더스',
 '5.5닭갈비',
 '60년전통 할매국밥',
 '63뷔페 파빌리온',
 '646테이블',
 '7HUNDRED',
 '88돼지',
 '88버거',
 '88생선구이',
 '8월의양',
 'BRCD',
 'C27',
 'JB파스타',
 'K375',
 'La Cour 1912',
 'PIZZA UP',
 'WE Ccafe',
 'e99',
 '가나안덕',
 '가디록',
 '가림시골밥상',
 '가마마루이',
 '가마솥보은순대',
 '가마솥족발',
 '가메골 손만두',
 '가미우동',
 '가배도',
 '가보정',
 '가비가배',
 '가시식당',
 '가시아방',
 '가야가야',
 '가야밀면',
 '가야성',
 '가양 칼국수',
 '가온',
 '가재골수제비',
 '가쯔레쯔',
 '가타쯔무리',
 '갈릴리농원',
 '갈비1987',
 '갈비씨',
 '갈현동할머니떡볶이',
 '감각의제국',
 '감나무집',
 '감나무집 기사식당',
 '감성타코',
 '감칠',
 '갓덴스시',
 '갓잇',
 '갓포아키',
 '강강술래',
 '강남',
 '강남곱',
 '강남면옥',
 '강남불백',
 '강릉가는길',
 '강릉감자옹심이',
 '강릉불고기',
 '강서면옥',
 '강원도 막국수',
 '강원도손순두부',
 '강촌숯불닭갈비',
 '강한고집',
 '강화국수',
 '강화손칼국수',
 '개군할머니 토종순대국',
 '개금밀면',
 '개돼지 크래프트 브루펍',
 '개미집',
 '개성집',
 '개천식당',
 '갯마을',
 '거멍국수',
 '거북이식당',
 '거인통닭',
 '건강한빵',
 '건도리횟집',
 '건봉국밥',
 '걸리버막창',
 '겁없는토끼부엌',
 '겐로쿠우동',
 '겐텐',
 '겟썸커피',
 '경미네집',
 '경발원',
 '경복궁',
 '경복궁삼계탕',
 '경상도집',
 '경성양육관',
 '경성함바그',
 '경양식1920',
 '경주식당',
 '경주콩이랑',
 '경평면옥',
 '곁집',
 '계림',
 '계림원',
 '계열사',
 '계절밥상',
 '계탄집',
 '계화기식당',
 '고가빈커리',
 '고객식당',
 '고구려 짬뽕',
 '고구려짬뽕10101',
 '고기굼터',
 '고기리 막국수',
 '고기창고',
 '고기튀김',
 '고냉지',
 '고니스',
 '고단백식당',
 '고담2015',
 '고래사어묵',
 '고려국시',
 '고려당',
 '고르드',
 '고른햇살',
 '고명집',
 '고베규카츠',
 '고산떡갈비',
 '고삼이',
 '고성막국수',
 '고씨네',
 '고양이부엌',
 '고옥',
 '고요남',
 '고자리냉면',
 '고자리칡냉면',
 '고주몽화로구이',
 '고집돌우럭',
 '고추만두국집',
 '고치소 라멘',
 '고치소사마',
 '고쿠텐',
 '고향나들이',
 '고향집',
 '고황24시뼈다귀해장국감자탕',
 '고흥순대국',
 '곤드레밥집',
 '곤트란 쉐리에',
 '골드코스트',
 '골목 떡볶이',
 '골목안채',
 '곰골식당',
 '곰설채 설렁탕',
 '곱',
 '곱창고',
 '공감식당',
 '공룡국수',
 '공릉동 닭한마리',
 '공복',
 '공주집',
 '공주칼국수',
 '공천포식당',
 '공평동 꼼장어',
 '공항칼국수',
 '공화춘',
 '광릉불고기',
 '광릉한옥집',
 '광주식당',
 '광천막국수',
 '광천식당',
 '광화문국밥',
 '광화문뚝감',
 '광화문살롱',
 '광화문집',
 '교다이야',
 '교대갈비집',
 '교대이층집',
 '교동반점',
 '교동집',
 '교동집밥',
 '교동짬뽕',
 '교리김밥',
 '교수곱창',
 '구공탄곱창',
 '구루몽',
 '구르미산도',
 '구복',
 '구복만두',
 '구스아일랜드 브루하우스',
 '구스토타코',
 '구워삶기',
 '구이구이',
 '구좌상회',
 '국물없는 우동',
 '국수마당',
 '국수바다',
 '국수찾아닭만리',
 '국시집',
 '국시집밀가마',
 '국일식당',
 '군산식당',
 '군포식당',
 '굴다리식당',
 '굴뚝집',
 '궁전제과',
 '권인순 갈비김치찌개',
 '귀락당',
 '규시',
 '그녀의밥상',
 '그늘집',
 '그다방',
 '그란데',
 '그래니살룬',
 '그레고리',
 '그로우',
 '그리고식당',
 '그리운바다 성산포',
 '그리지하우스',
 '그릴휘바',
 '그림같은빵집',
 '그림나베',
 '그릿비 일광',
 '그집',
 '글로우',
 '글린공원',
 '금강막국수',
 '금돼지식당',
 '금룡',
 '금수복국',
 '금암소바',
 '금오식당',
 '금왕돈까스',
 '금왕평양면옥',
 '금용',
 '금학칼국수',
 '금화루',
 '기꾸스시',
 '기다스시',
 '기리야마',
 '기성면옥',
 '기와집순두부',
 '기와탭룸',
 '기욤',
 '기장손칼국수',
 '기차길옆초밥',
 '긴자 바이린',
 '길거리야',
 '길목',
 '길버트버거',
 '김네집',
 '김덕후의곱창조',
 '김도사불백',
 '김돈이',
 '김부삼',
 '김삿갓',
 '김수사',
 '김영섭초밥',
 '김영애 할머니순두부',
 '김영태의이자카야마을',
 '김우정 초당짬뽕순두부',
 '김태완스시',
 '김통',
 '김희선 몸국',
 '까꾸네 모리국수',
 '까사',
 '까이식당',
 '까치둥지',
 '깔리',
 '깡우동',
 '깡촌흑돼지',
 '깡통돌곱창',
 '깡통만두',
 '꼬꼬아찌숯불치킨',
 '꼭그닭',
 '꽁당보리밥',
 '꽃돌게장1번가',
 '꽃돼지 갤러리',
 '꽃볶이',
 '꾸띠자르당',
 '꾸바꾸바',
 '꿀삼겹',
 '뀌숑',
 '나누미 떡볶이',
 '나랏님',
 '나랑가',
 '나리의집',
 '나무사이로',
 '나베나루',
 '나베식당',
 '나이스샤워',
 '나이쏘이',
 '나인로드 피제리아',
 '나인블럭',
 '나인온스버거',
 '나주곰탕 하얀집',
 '나지미돈부리',
 '나폴레옹과자점',
 '낙산냉면',
 '낙선재',
 '낙성곱창',
 '낙영찜갈비',
 '낙원타코',
 '낙지마실',
 '남경막국수',
 '남도분식',
 '남도예담',
 '남북면옥',
 '남성집',
 '남자마늘보쌈',
 '남포면옥',
 '낭뜰에쉼팡',
 '낭만카페',
 '내사랑 동까스',
 '냉수탕가든',
 '너도나도식당',
 '네거리식당',
 '녘',
 '노가리슈퍼',
 '노라바',
 '노르웨이식당',
 '노원 돈부리',
 '노홍만두',
 '녹차고을',
 '논골추어탕',
 '놀맨',
 '놈파스타',
 '농민백암순대',
 '농부쌈밥',
 '농부핏자',
 '농촌순두부',
 '뇌조리국수집',
 '누메로도스',
 '누오보나폴리',
 '누하의숲',
 '눈나무집',
 '뉴욕반점',
 '뉴욕비앤비',
 '뉴질랜드스토리',
 '느린마을 양조장',
 '늘봄흑돼지',
 '늘해랑',
 '능두네',
 '능라도',
 '니고라멘',
 '니드썸레스트',
 '니뽕내뽕',
 '닐모리 동동',
 '닝교초식당',
 '다락투',
 '다래',
 '다래옥',
 '다래함박스텍',
 '다로베',
 '다리집',
 '다미',
 '다야',
 '다우랑',
 '다운타우너',
 '다이닝 인 스페이스',
 '다이도코로',
 '다전식당',
 '다정이네',
 '다츠',
 '다케',
 '다케다야',
 '다케오 호르몬 데판야끼',
 '닥터로빈',
 '단골집',
 '단디',
 '단바쿠라멘',
 '단양마늘만두',
 '단천식당',
 '단콩',
 '달빛식탁',
 '달콤한 거짓말',
 '닭꼬얌',
 '닭발의지존',
 '닭발집',
 '닭칼원조집',
 '닷지',
 '당근마차',
 '당도',
 '당산옛날곱창',
 '닻',
 '대가방',
 '대게나라',
 '대관원',
 '대구갈비',
 '대궐쌈밥',
 '대길고추불고기',
 '대낚식당',
 '대도식당',
 '대독장',
 '대동면옥',
 '대림창고',
 '대막',
 '대머리곱창',
 '대문점',
 '대보명가',
 '대선칼국수',
 '대성갈비',
 '대성집',
 '대왕김밥',
 '대우식당',
 '대우칼국수',
 '대원당',
 '대정양곱창',
 '대치순대국',
 '대통삼',
 '대한옥',
 '대호정',
 '대화만두',
 '댄싱카페인',
 '더 가든 키친',
 '더 썸머 방콕',
 '더 파크뷰',
 '더꽃돈',
 '더다이닝랩',
 '더라운드',
 '더멜팅팟',
 '더백푸드트럭',
 '더버뮤다',
 '더베이커스테이블',
 '더블트러블',
 '더스트릿',
 '더식당',
 '더아리엘',
 '더앨리',
 '더캐스크',
 '더키친 살바토레 쿠오모',
 '더테이블',
 '더티트렁크',
 '더페이머스버거',
 '더포',
 '더푸드하우스',
 '더플레이스',
 '더피자보이즈',
 '더핸드',
 '덕자네방앗간',
 '던킨도너츠',
 '데블스도어',
 '데코아 발림',
 '델문도',
 '뎀셀브즈',
 '뎁짜이',
 '도군함박',
 '도동집',
 '도두해녀의집',
 '도락',
 '도렐',
 '도리도리하찌',
 '도마',
 '도마29',
 '도산분식',
 '도셰프',
 '도솔마을',
 '도스타코스',
 '도우룸 바이 스와니예',
 '도원경',
 '도제',
 '도치피자',
 '도쿄다이닝',
 '도쿄등심',
 '도쿄빙수',
 '도쿄스테이크',
 '도쿄파스타',
 '도토리브라더스',
 '도프셰프',
 '독',
 '독도네꼬막',
 '독도쭈꾸미',
 '독립카츠',
 '독일주택',
 '독천식당',
 '돈까스먹는 용만이',
 '돈까스백반',
 '돈까스상회',
 '돈까스의 집',
 '돈까스잔치',
 '돈돈',
 '돈돈정',
 '돈부리모노',
 '돈부리청년',
 '돈사돈',
 '돈이랑',
 '돈천동식당',
 '돈코보쌈',
 '돕감자탕',
 '동경미식',
 '동경우동',
 '동굴화로구이',
 '동기간',
 '동남집',
 '동도원',
 '동동국수집',
 '동리장',
 '동명항 생선숯불구이',
 '동명항 전복해물뚝배기',
 '동무밥상',
 '동북화과왕',
 '동빙고',
 '동서네낙지',
 '동숭동커피',
 '동아냉면',
 '동원집',
 '동이손만두',
 '동차밥',
 '동탄곤드레',
 '동해도',
 '동해막국수',
 '동해원',
 '동해장',
 '동해해물',
 '동화가든',
 '동흥관',
 '돼지바',
 '돼지집',
 '두꺼비게장',
 '두꺼비식당',
 '두꺼비집',
 '두끼',
 '두레국수',
 '두물머리연핫도그',
 '두배갈비',
 '두툼',
 '두화당',
 '듀',
 '듀윗',
 '듀자미',
 '드럼스틱',
 '들밥',
 '등뼈',
 '등촌샤브칼국수',
 '디에이프릴',
 '디저트홀릭',
 '디차이나',
 '디트로네',
 '딘타이펑',
 '딤딤섬',
 '딥블루레이크',
 '딴뚝통나무집',
 '딸랏롯빠이',
 '딸부자네불백',
 '땀땀',
 '땅코참숯구이',
 '땡이네소곱창',
 '떡도리탕',
 '떡볶이창고',
 '떡싸롱',
 '또보겠지떡볶이',
 '또순이 원조 순대',
 '또순이네',
 '또이또이베트남',
 '똑순이아구찜',
 '뚜스뚜스',
 '뚜쥬루',
 '뚝떡',
 '뚝배기집',
 '뚱보집',
 '뚱보할매김밥',
 '라 플랑끄',
 '라공방',
 '라구뜨',
 '라구식당',
 '라그릴리아',
 '라디오베이',
 '라뜰리에 김가',
 '라라관',
 '라라브레드',
 '라라코스트',
 '라멘모토',
 '라멘미세',
 '라멘베라보',
 '라멘우에무라',
 '라멘트럭',
 '라면 땡기는 날',
 '라시에스타',
 '라에스키나',
 '라연',
 '라운드어바웃',
 '라이너스바베큐',
 '라치오',
 '라크라센타',
 '라페름',
 '라화쿵부',
 '라화쿵푸',
 '락원',
 '란주라미엔',
 '란주탕슉',
 '랑데자뷰',
 '러스트 베이커리',
 '러시안',
 '런드리피자',
 '렁팡스',
 '레드락',
 '레어마카롱',
 '레이식당',
 '레이어드',
 '레호이',
 '로네펠트',
 '로니로티',
 '로마레스토랑',
 '로빈의숲',
 '로스옥',
 '로우 커피 스탠드',
 '로우슬로우',
 '로운',
 '로이타이',
 '로지로키로드',
 '로타리식당',
 '롤링 파스타',
 '롤링파스타',
 '롱브레드',
 '루소랩',
 '루프엑스',
 '류 (Ryu)',
 '류재은베이커리',
 '르 번미',
 '르 쁘띠 푸',
 '르블란서',
 '르사이공',
 '르풀',
 '리미니',
 '리북집',
 '리안',
 '리에또',
 '리에제 와플 (림벅와플)',
 '리차드카피캣',
 '리치망고',
 '리틀넥',
 '리틀이태리',
 '리틀파스타',
 '리틀파파',
 '리틀파파포',
 '리화인와플',
 '릴린',
 '마구로 쇼쿠도',
 '마끼노차야',
 '마녀주방',
 '마노 디 셰프',
 '마노디셰프',
 '마농치킨',
 '마늘석갈비막국수',
 '마담파이',
 '마당플라워 카페',
 '마더린러 베이글',
 '마라공방',
 '마렘마',
 '마루가메 제면',
 '마루심',
 '마리스',
 '마린칸토',
 '마마돈',
 '마마된장',
 '마마부찌',
 '마방집',
 '마복림 떡볶이',
 '마시앤바시',
 '마시찜',
 '마야양고기',
 '마약떡볶이',
 '마얘',
 '마이란',
 '마이무',
 '마이알레',
 '마이첼시',
 '마이클식당',
 '마쯔미라멘',
 '마초쉐프',
 '마카나이',
 '마쿠 (구.양국복마라탕)',
 '마키진',
 '마포본가',
 '마포원조떡볶이',
 '마포원조최대포',
 '마피아디저트',
 '마호가니',
 '막내횟집',
 '만고쿠',
 '만나분식',
 '만다복',
 '만덕이네',
 '만두집',
 '만석닭강정',
 '만선호프',
 '만성복집',
 '만성양꼬치',
 '만옥당',
 '만월당',
 '만족오향족발',
 '만푸쿠',
 '맘마미아',
 '맘맘테이블',
 '맛나게장',
 '맛나곱창',
 '맛나식당',
 '맛이차이나',
 '맛있는 발효밥상 궁뜰',
 '맛집곱창구이',
 '맛찬들왕소금구이',
 '망원동 즉석우동',
 '망원동티라미수',
 '망향비빔국수',
 '매그놀리아',
 '매뉴팩트커피',
 '매덕스피자',
 '매드포갈릭',
 '매란방',
 '매운향솥',
 '매일식당',
 '매향',
 '매화반점',
 '매화쌈밥',
 '맨도롱 식당',
 '맨션5',
 '맵군',
 '맷돌순두부',
 '머내 돌삼겹살',
 '먹보한우',
 '메드포갈릭',
 '메밀공방',
 '메밀랑',
 '메밀방앗간',
 '메밀향그집',
 '메이드바이오즈',
 '메이란',
 '메이비',
 '메이플가든',
 '메종 엠오',
 '메콩타이',
 '멘무샤',
 '멘야 산다이메',
 '멘야마쯔리',
 '멘야산다이메',
 '멘야하나비',
 '멘쯔',
 '멜로워',
 '멜팅샵',
 '면뽑는선생 만두빚는아내',
 '면주방',
 '명가양꼬치',
 '명동교자',
 '명동닭한마리',
 '명동돈가스',
 '명동우미닭갈비',
 '명동쫄면',
 '명동찌개마을',
 '명동피자',
 '명랑스낵',
 '명륜건강원',
 '명문제과',
 '명봉반점',
 '명서밀면',
 '명성닭강정',
 '명성불고기',
 '명작가',
 '명태미가',
 '명품순두부',
 '명화 식육식당',
 '명화당',
 '모꼬지에',
 '모녀떡볶이',
 '모다모다',
 '모닥식탁',
 '모던기와',
 '모던테이블',
 '모래비카페',
 '모로코코 카페',
 '모루',
 '모루식당',
 '모모스',
 '모모스테이크',
 '모연',
 '모자호떡',
 '모터시티',
 '모힝',
 '목동분식',
 '목란',
 '목멱산방',
 '목천집',
 '목포고을',
 '목포명가',
 '목포집',
 '목향원',
 '몬스터피자',
 '몽상드애월',
 '몽화가락',
 '묘향손만두',
 '무교동 북어국집',
 '무등산 닭한마리',
 '무라',
 '무라텐',
 '무르무르 드 구스토',
 '무수옥',
 '무월',
 '무월식탁',
 '무차초',
 '묵전',
 '문',
 '문배동육칼',
 '문쏘',
 '문어부인삼교비',
 '문토스트',
 '문호리팥죽',
 '문화식당',
 '물레방아',
 '물항식당',
 '뭄알로이',
 '미가',
 '미가양고기',
 '미가연',
 '미나리식당',
 '미나미',
 '미담진족',
 '미드레벨',
 '미림 식당',
 '미미국수',
 '미미루',
 '미미면가',
 '미미미',
 '미미향',
 '미분당',
 '미쁜식탁',
 '미사리밀빛 초계국수',
 '미성식당',
 '미성옥',
 '미세노센세',
 '미소가짬뽕',
 '미소복 양평 해장국',
 '미술관옆집',
 '미스터서왕만두',
 '미스터스시',
 '미스트',
 '미스티크',
 '미스피츠',
 '미쓰리 부대찌개',
 '미쓰발랑코',
 '미쓰족발',
 '미애네',
 '미야꼬우동',
 '미엔아이',
 '미엘',
 '미연마라탕',
 '미영이네 식당',
 '미우치',
 '미자식당',
 '미진',
 '미진돌곱창',
 '미진분식',
 '미풍해장국',
 '믹스앤몰트',
 '민들레처럼',
 '민벅',
 '민쿡다시마',
 '민쿡의 화덕쭈꾸미',
 '밀도',
 '밀빛초계국수',
 '밀양순대돼지국밥',
 '밀탑',
 '밀토스트',
 '바나나테이블',
 '바나나하루키',
 '바네스데코 카페',
 '바네스타코',
 '바다다',
 '바다속고등어쌈밥',
 '바다식당',
 '바다정원',
 '바다파스타',
 '바다회사랑',
 '바로그집',
 '바로방',
 '바르미',
 '바르미 샤브샤브',
 '바른식',
 '바리스타빈',
 '바베큐캠프',
 '바비레드',
 '바빌리안테이블',
 '바숨키친',
 '바스버거',
 '바스코',
 '바오밥',
 '바이킹스워프',
 '바토스',
 '박가네 빈대떡',
 '박군자 진주냉면',
 '박서방 순대국밥',
 '박용석스시',
 '반갱',
 '반구정 나루터집',
 '반룡산',
 '반미리코',
 '반쥴',
 '반포식스',
 '반포치킨',
 '발리비스트로',
 '발리인망원',
 '발산삼계탕',
 '밤부카페',
 '밥깡패',
 '밥에큐',
 '방동막국수',
 '방이샤브샤브칼국수',
 '방콕야시장',
 '방콕익스프레스',
 '배꼽집',
 '배니닭강정',
 '배드파머스',
 '배신식당',
 '배키욘방',
 '백금당',
 '백년식당',
 '백년옥',
 '백로식당',
 '백리향',
 '백만석',
 '백부장집닭한마리',
 '백암왕순대',
 '백운봉막국수',
 '백제정육점',
 '백촌막국수',
 '백합칼국수',
 '백화양곱창',
 '뱃고동',
 '뱃놈',
 '버거307',
 '버거비',
 '버거앤파스타',
 '버거인뉴욕',
 '버거톤',
 '버거파크',
 '버드나무브루어리',
 '버드나무집',
 '버터밀크',
 '버터핑거 팬케이크',
 '버터핑거 팬케익스',
 '번패티번',
 '벌집칼국수',
 '범가',
 '베러댄비프',
 '베리스트릿키친',
 '베스타',
 '베테랑',
 '베트남고향식당',
 '벤자마스',
 '벵디',
 '변가네 옹진냉면',
 '별난 면옥',
 '별미곱창',
 '별채반 교동쌈밥',
 '보나카바',
 '보니스피자펍',
 '보리네주먹고기',
 '보배곱창',
 '보사노바',
 '보스대게',
 '보영만두',
 '보헤미안 박이추 커피',
 '복돈이부추삼겹살',
 '복성각',
 '복성루',
 '복성반점',
 '복성원',
 '복자씨연탄구이',
 '복정집',
 '본수원',
 '본순대국',
 '본전돼지국밥',
 '본토닭갈비',
 '볼트 스테이크하우스',
 '봄날 카페',
 '봉가진면옥',
 '봉덕칼국수',
 '봉밀가',
 '봉봉방앗간',
 '봉브레드',
 '봉산찜갈비',
 '봉선마라탕',
 '봉순게장',
 '봉순이네 흑돼지',
 '봉스시',
 '봉용불고기',
 '봉우이층집',
 '봉우화로',
 '봉이만두',
 '봉자마라탕',
 '봉쥬르하와이',
 '봉추찜닭',
 '봉평메밀면옥',
 '봉포머구리집',
 '봉피양',
 '봉화산설렁탕',
 '봉희설렁탕',
 '부다스벨리',
 '부두식당',
 '부띠끄경성',
 '부부식당',
 ...]

CF로 추천하기

In [36]:
# 비슷한 item만 추천에 사용
ratings_pred = predict_rating_topsim(ratings_matrix.values, item_sim_df.values, n = 5)

ratings_pred_matrix = pd.DataFrame(data = ratings_pred, index = ratings_matrix.index, columns = ratings_matrix.columns)

# item 기반의 KNN CF로 추천
recomm_store = recomm_store_by_user(ratings_pred_matrix, 293161, not_visit, top_n = 5)
recomm_store = pd.DataFrame(data=recomm_store.values, index=recomm_store.index, columns = ["score"])

<ipython-input-32-b164be74c04f>:10: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  pred[row, col] = item_sim_arr[col, :][top_n_items].dot(ratings_arr[row, :][top_n_items].T)
<ipython-input-32-b164be74c04f>:11: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  pred[row, col] /= np.sum(item_sim_arr[col, :][top_n_items])

Index(['애정훠궈', '강릉감자옹심이', '오뗄두스', '아찌떡볶이', '달콤한 거짓말'], dtype='object', name='store_name')

In [37]:
for name in recomm_store.index:
    print(name)

애정훠궈
강릉감자옹심이
오뗄두스
아찌떡볶이
달콤한 거짓말